baseURL = 'https://nguyenkhachoan.com/'
languageCode = 'en-us'
title = 'NoLih Site'
theme = "hello-friend-ng"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
paginate = 10
rssLimit = 10  # Maximum number of items in the RSS feed.
archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = false
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false

[permalinks]
    posts = "/posts/:year/:month/:title/"

[author]
    name = "NoLih"

[blackfriday]
    hrefTargetBlank = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    description = "Nice theme for homepages and blogs"
    keywords = ""
    images = [""]
    homeSubtitle = "My site about me ðŸ¥"
    disableReadOtherPosts = false
    enableThemeToggle = true
    enableSharingButtons = true
    enableGlobalLanguageMenu = false
    customCSS = []
    customJS = []
    justifyContent = false  # Set "text-align: justify" to .post-content.
    [params.footer]
        trademark = true
        rss = true
        copyright = true
        author = true
    topText = []
    bottomText = []
    [params.logo]
        logoMark = ">"
        logoText = "nolih"
        logoHomeLink = "/"
    [[params.social]]
        name = "email"
        url = "mailto:hoanuchiha98@gmail.com"
    [[params.social]]
        name = "github"
        url = "https://github.com/hoanuchiha98"
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/hoannk9x/"
    weight = 1
[menu]
    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts/"
